### ISSUE TITLE
Getting issues with 0.3.8

### ISSUE THREAD

**Issue by itssumitrai** [yahoo/react-dnd-touch-backend#60]
Seeing build issues with latest version
```
ReferenceError: document is not defined
        at Object.<anonymous> (/home/cat/ecapp/node_modules/react-dnd-touch-backend/dist/Touch.js:72:4)
        at Module._compile (module.js:570:32)
        at Module._extensions..js (module.js:579:10)
        at Object.require.extensions.(anonymous function) [as .js] (/home/cat/ecapp/node_modules/babel-register/lib/node.js:152:7)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/home/cat/ecapp/components/toolbar/CustomColumns/ReorderColumns.jsx:8:1)
        at Module._compile (module.js:570:32)
        at loader (/home/cat/ecapp/node_modules/babel-register/lib/node.js:144:5)
        at Object.require.extensions.(anonymous function) [as .jsx] (/home/cat/ecapp/node_modules/babel-register/lib/node.js:154:7)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
    Waiting for the debugger to disconnect...
```

**Comment by longlho** [comment]
this is only meant for client side

**Comment by itssumitrai** [comment]
Same code works fine with 0.3.7 though. Need to dig a little more.

**Comment by JoaoMosmann** [comment]
Can you tell us what is the use case? It shouldn't be throwing this error.

**Comment by JoaoMosmann** [comment]
Ok, I got it. `document` is being called at the library instantiation. I'll do a PR fixing it.

**Comment by itssumitrai** [comment]
Thanks @JoaoMosmann 👍

**Comment by longlho** [comment]
`0.3.9` published, should address this issue
