### ISSUE TITLE
Server side rendering broken

### ISSUE THREAD

**Issue by davidjmurphyjr** [yahoo/react-dnd-touch-backend#68]
Hi there,

This repo work flawlessly for me in the browser, however I am running into an issue with server side rendering.

```
ReferenceError: document is not defined
    at Object.<anonymous> (C:\gradifi\www\node_modules\react-dnd-touch-backend\dist\Touch.js:72:9)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\gradifi\www\node_modules\babel-register\lib\node.js:152:7)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:/gradifi/www/member/components/loan/ActiveLoanList.js:11:1)
```

The relevant code:
```
// Polyfill for document.elementsFromPoint
var elementsFromPoint = (typeof document !== 'undefined' && document.elementsFromPoint || function (x, y) {
    ...
}).bind(document);
```

The issue:
On the node.js side, `document` does not exist so the code bombs.

Possible solution:
Is the `.bind(document)` necessary? The elementsFromPoint function never references "this". I propose removing `.bind(document)`.

Side note:
Is this really a polyfill? In the only place were this function is called (line 408), the code refers to the local `var elementsFromPoint` as opposed to `document.elementsFromPoint`

**Comment by JoaoMosmann** [comment]
Hi, thanks for reporting it.
I commented in your PR, have a look.

Yes, it's a "polyfill", it could be stored in the document. So it's more a fallback, but I don't see many differences.

**Comment by davidjmurphyjr** [comment]
Yup, you're totally right, it is a polyfill, I misunderstood what that first line was doing.

**Comment by JoaoMosmann** [comment]
Should be working on `v0.3.11`
